import Head from "next/head";

import Navbar from "../pages/components/navbar";
import Mainbanner from "../pages/components/main-banner";

export default function Home() {
  return (
    <>
      <Head>
        <title>Stitches Crash Course</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navbar />
        <Mainbanner />
      </main>
    </>
  );
}
