import Head from "next/head";

import Navbar from "../pages/components/navbar";
import Mainbanner from "../pages/components/main-banner";
import TeamsBox from "../pages/components/teams";
import Heroimage from "../pages/components/heroimage";
import LetsBuildSection from "../pages/components/letsbuild";
import AvailableFor from "../pages/components/available-for";
import IdentityProvidersSection from "../pages/components/identity-providers";
import MainAction from "../pages/components/main-cta";

export default function Home() {
  return (
    <>
      <Head>
        <title>Stitches Crash Course</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navbar />
        <Mainbanner /> 
        <TeamsBox />
        <Heroimage />
        <LetsBuildSection />
        <AvailableFor />
        <IdentityProvidersSection />
        <MainAction />
      </main>
    </>
  );
}
